---
name: The Compliance Academy
title: The Compliance Academy
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
url: http://www.thecompliance.academy
baseurl: ''
# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
