---
title: The Compliance Academy
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
name: The Compliance Academy
url: http://www.thecompliance.academy
baseurl: ''
permalink: "/:title/"
markdown: kramdown
theme: minima
plugins:
- jekyll-feed
